### ISSUE TITLE
Issue when running ./gradlew check

### ISSUE THREAD

**Issue by MamboBryan** [mpetuska/template-kmp-library#116]
Found these issues when running `./gradlew check` it fails only for browser 

<img width="704" alt="Screenshot 2023-08-17 at 12 05 53 PM" src="https://github.com/mpetuska/template-kmp-library/assets/40160345/b76a0633-43c5-4f59-8bfa-9853d61bd5c7">

<img width="985" alt="Screenshot 2023-08-17 at 12 02 54 PM" src="https://github.com/mpetuska/template-kmp-library/assets/40160345/3554934b-af36-4286-bf55-6ab69361d2cf">

**Comment by mpetuska** [comment]
Seems you don't have chromium browser installed to run tests on. You can change the browser for tests in gradle.properties (e.g. firefox-headless, chrome-headless, edge-headless)
